[package]
name = "acm_discord_bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }